-- SALONIQ demo schema for Supabase. Safe to run more than once.
create extension if not exists "uuid-ossp";

create table if not exists public.shops (
  id bigint generated by default as identity primary key,
  shop_name text not null, address text, phone_number text, email text,
  owner_name text, logo_url text, is_available boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  user_name text unique not null, full_name text, email text not null,
  role text not null check (role in ('SUPER_ADMIN','ADMIN','STAFF','CUSTOMER')),
  shop_id bigint references public.shops(id) on delete set null,
  phone_number text, date_of_birth date, photo_url text,
  specialties text[] not null default '{}', rating numeric(3,2) not null default 0,
  available boolean not null default true, working_start time default '09:00',
  working_end time default '18:00', first_login boolean not null default true,
  is_active boolean not null default true, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shops(id) on delete cascade,
  service_name text not null, category text not null, description text,
  total_price numeric(12,2) not null default 0 check (total_price >= 0),
  duration_minutes integer not null default 30 check (duration_minutes > 0),
  gender_applicable text not null default 'UNISEX' check (gender_applicable in ('MALE','FEMALE','UNISEX')),
  photo_url text, is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.staff_members (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  name text not null, role text not null, photo text,
  available boolean not null default true,
  specialties text[] not null default '{}', rating numeric(3,2) not null default 0,
  next_available timestamptz, working_start time default '09:00', working_end time default '18:00',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  name text not null, phone text not null, email text,
  gender text check (gender in ('male','female','other')),
  visit_count integer not null default 0, last_visit timestamptz,
  total_spent numeric(12,2) not null default 0, pending_amount numeric(12,2) not null default 0,
  preferred_services text[] not null default '{}', notes text, photo text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (shop_id, phone)
);

create table if not exists public.appointments (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null, customer_phone text,
  employee_id uuid references public.profiles(id) on delete set null, employee_name text,
  service_ids bigint[] not null default '{}', service_names text[] not null default '{}',
  appointment_date date not null, appointment_time time not null,
  status text not null default 'scheduled' check (status in ('scheduled','in_progress','completed','cancelled')),
  total numeric(12,2) not null default 0, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.appointments
  add column if not exists staff_member_id uuid references public.staff_members(id) on delete set null;

create table if not exists public.inventory_items (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  name text not null, category text, brand text,
  stock integer not null default 0 check (stock >= 0),
  in_use_stock integer not null default 0 check (in_use_stock >= 0),
  min_threshold integer not null default 5 check (min_threshold >= 0),
  price numeric(12,2) not null default 0, image text, description text,
  updated_at timestamptz not null default now(), created_at timestamptz not null default now()
);

create table if not exists public.inventory_in_use (
  id uuid primary key default uuid_generate_v4(),
  item_id uuid not null references public.inventory_items(id) on delete cascade,
  quantity integer not null check (quantity > 0), assigned_station text,
  opened_date date not null default current_date, notes text, created_at timestamptz not null default now()
);

create table if not exists public.store_products (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  name text not null, category text, brand text,
  price numeric(12,2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0), image text, description text,
  status text not null default 'active' check (status in ('active','out_of_stock','draft')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.store_orders (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  order_number text unique not null, customer_name text not null, customer_phone text not null,
  delivery_type text not null check (delivery_type in ('pickup','delivery')), address text,
  total_amount numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('cash','card','upi')),
  payment_status text not null default 'pending' check (payment_status in ('pending','completed')),
  order_status text not null default 'pending' check (order_status in ('pending','processing','completed','cancelled')),
  notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.store_order_items (
  id uuid primary key default uuid_generate_v4(), order_id uuid not null references public.store_orders(id) on delete cascade,
  product_id uuid references public.store_products(id) on delete set null,
  product_name text not null, product_image text, price numeric(12,2) not null,
  quantity integer not null check (quantity > 0)
);

create table if not exists public.tally_items (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  entry_date date not null default current_date, entry_time time not null default localtime,
  customer_name text not null, customer_phone text, staff_name text,
  services jsonb not null default '[]'::jsonb, total_cost numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('cash','card','upi')),
  payment_status text not null default 'pending' check (payment_status in ('pending','completed','failed','cancelled')),
  payment_date date, upi_transaction_id text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default uuid_generate_v4(),
  shop_id bigint not null references public.shops(id) on delete cascade,
  title text not null, category text, amount numeric(12,2) not null check (amount >= 0),
  expense_date date not null default current_date, notes text, created_at timestamptz not null default now()
);

create index if not exists appointments_shop_date_idx on public.appointments(shop_id, appointment_date);
create index if not exists customers_shop_phone_idx on public.customers(shop_id, phone);
create index if not exists orders_shop_created_idx on public.store_orders(shop_id, created_at desc);

alter table public.shops enable row level security;
alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.staff_members enable row level security;
alter table public.customers enable row level security;
alter table public.appointments enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_in_use enable row level security;
alter table public.store_products enable row level security;
alter table public.store_orders enable row level security;
alter table public.store_order_items enable row level security;
alter table public.tally_items enable row level security;
alter table public.expenses enable row level security;

do $$ declare t text; begin
  foreach t in array array['shops','profiles','services','staff_members','customers','appointments','inventory_items','inventory_in_use','store_products','store_orders','store_order_items','tally_items','expenses'] loop
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='authenticated_manage') then
      execute format('create policy authenticated_manage on public.%I for all to authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='shops' and policyname='public_read_shops') then create policy public_read_shops on public.shops for select to anon using (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='services' and policyname='public_read_services') then create policy public_read_services on public.services for select to anon using (is_active = true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='staff_members' and policyname='public_read_available_staff') then create policy public_read_available_staff on public.staff_members for select to anon using (available = true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='store_products' and policyname='public_read_store_products') then create policy public_read_store_products on public.store_products for select to anon using (status = 'active'); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='customers' and policyname='public_create_customers') then create policy public_create_customers on public.customers for insert to anon with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='appointments' and policyname='public_create_appointments') then create policy public_create_appointments on public.appointments for insert to anon with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='store_orders' and policyname='public_create_orders') then create policy public_create_orders on public.store_orders for insert to anon with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='store_order_items' and policyname='public_create_order_items') then create policy public_create_order_items on public.store_order_items for insert to anon with check (true); end if;
end $$;

insert into public.shops (id, shop_name, address, phone_number, email, owner_name, is_available)
values (1,'SALONIQ','Koregaon Park, Pune','+91 98765 43210','hello@saloniq.demo','Demo Owner',true)
on conflict (id) do nothing;

insert into public.services (id, shop_id, service_name, category, description, total_price, duration_minutes, gender_applicable)
values
  (1,1,'Haircut & Style','Hair','Professional haircut and styling with blow dry',500,60,'UNISEX'),
  (2,1,'Hair Color','Hair','Full hair coloring with premium products',3500,120,'UNISEX'),
  (3,1,'Facial Treatment','Skin Care','Deep cleansing facial with mask and massage',2500,90,'UNISEX'),
  (4,1,'Manicure','Nails','Classic manicure with nail shaping and polish',800,45,'UNISEX')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.shops','id'), greatest((select coalesce(max(id),1) from public.shops),1));
select setval(pg_get_serial_sequence('public.services','id'), greatest((select coalesce(max(id),1) from public.services),1));
