spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SUPABASE_DB_URL:jdbc:mysql://localhost:3306/slon1}
spring.datasource.username=${SUPABASE_DB_USER:username}
spring.datasource.password=${SUPABASE_DB_PASSWORD:password}
spring.datasource.driver-class-name=${SUPABASE_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# JWT secret key
jwt.secret=jwt.secret=Th1sIsAVery$trongS3cretKeyWith123Symbols!

server.error.whitelabel.enabled=false

server.port=8080
server.address=0.0.0.0



# email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourEmail
app.mail.from=yourEmail
spring.mail.password=AppPass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# FreeMarker template config (optional)
spring.freemarker.template-loader-path=classpath:/template/mail/
spring.freemarker.suffix=.ftl
spring.freemarker.charset=UTF-8
spring.freemarker.check-template-location=true

##messages properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8


logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO

# Upload folder (relative to project root or absolute path)
file.upload-dir=C:/opt/shop-crm/uploads/

# Allow large file sizes if needed
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB





